# Generated by Django 5.1.1 on 2025-01-07 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_management', '0001_initial'),
        ('vault', '0019_alter_teamvaultactionrequest_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('reused_passwords_count', models.IntegerField(default=0)),
                ('similar_passwords_count', models.IntegerField(default=0)),
                ('breached_passwords_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.vault')),
            ],
            options={
                'verbose_name_plural': 'Password Analyses',
            },
        ),
        migrations.CreateModel(
            name='PasswordIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('reused', 'Reused Password'), ('similar', 'Similar Password'), ('breached', 'Breached Password')], max_length=10)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='password_management.passwordanalysis')),
                ('login_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.logininfo')),
            ],
        ),
    ]
