# Generated by Django 5.1.1 on 2025-01-09 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_invitation'),
        ('password_management', '0002_passwordanalysis_passwordissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordanalysis',
            name='vault',
        ),
        migrations.AddField(
            model_name='passwordanalysis',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaboration.team'),
        ),
    ]
