# Generated by Django 5.1.1 on 2025-01-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_management', '0003_remove_passwordanalysis_vault_passwordanalysis_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordanalysis',
            name='team',
        ),
    ]
