# Generated by Django 5.1.1 on 2024-09-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='logininfo',
            name='item',
        ),
        migrations.RemoveField(
            model_name='logininfo',
            name='login_password',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='LoginInfo',
        ),
        migrations.DeleteModel(
            name='LoginPassword',
        ),
        migrations.DeleteModel(
            name='Vault',
        ),
    ]
