# Generated by Django 5.1.1 on 2024-10-15 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
        ('vault', '0004_vault_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to='collaboration.team'),
        ),
    ]
