# Generated by Django 5.1.1 on 2024-10-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_shareditem_sharedvault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_content',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='shareditem',
            name='share_link',
            field=models.CharField(default='pb7LDGxdjs', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedvault',
            name='share_link',
            field=models.CharField(default='pb7LDGxdjs', max_length=100, unique=True),
        ),
    ]
