# Generated by Django 5.1.1 on 2024-11-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_alter_shareditem_share_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareditem',
            name='share_link',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedvault',
            name='share_link',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
