# Generated by Django 5.1.1 on 2024-11-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0012_alter_shareditem_share_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
