# Generated by Django 5.1.1 on 2024-12-18 17:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0014_teamactionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamActionRequest',
            new_name='TeamVaultActionRequest',
        ),
    ]
