# Generated by Django 5.1.1 on 2024-12-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0016_rename_action_type_teamvaultactionrequest_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamvaultactionrequest',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=10),
        ),
    ]
