# Generated by Django 5.1.1 on 2024-12-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0018_rename_updated_at_teamvaultactionrequest_authorized_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamvaultactionrequest',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10),
        ),
    ]
